### PR TITLE
fix setting params

### PR DESCRIPTION
**Pull request by korylprince**
Set const directly instead of trying to get them from URL params.

### CODE REVIEW

**Comment by zacharyvenghaus** [comment]
Thank you Kory, but you're speaking Greek to me. lol.
Zachary R. Venghaus
Columbus ISD Director of Technology
979.732.5704 ext 111
zachary.venghaus@cisdschools.org
...Preparing today's students to succeed in tomorrow's world.

*"Often when you think you’re at the end of something, you’re at the
beginning of something else." ~ Fred Rogers*

CONFIDENTIALITY NOTICE: This e-mail, and any attachment, is intended only
for the person or entity to which it is addressed and may contain
confidential and/or privileged material. Any review, re-transmission,
copying, dissemination or other use of this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please return it to the sender and delete the material from
any computer. Columbus ISD will not be held responsible for the contents,
accuracy, completeness or validity of any information contained within this
message.

**Comment by korylprince** [comment]
Lol, you just need to merge this PR. There should be a merge button somewhere on this page for you. 

That will pull the code change I sent. 

Edit: here's a how-to: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

Any of the merge options will work.

**Comment by korylprince** [comment]
You can also see the exact changes I made here: https://github.com/zacharyvenghaus/columbusisd-covid-tracking/pull/1/commits/af906af1042873b07025f9c62970f8b3df065f50

**Review by zacharyvenghaus — APPROVED** [review]
Thank you!

**Pull request closed without merging**
